adj_1 = input("Enter an adjective")
adj_2 = input("Enter an adjective")
noun_1 = input("Enter a noun")
noun_2 = input("Enter a noun")
noun_3 = input("Enter a noun")
noun_4 = input("Enter a noun")
noun_5 = input("Enter a noun")
verb_1 = input("Enter a verb")
verb_2 = input("Enter a verb")
print("Here is your story below:")
print("My winter break was " + adj_1 + ". I was staying at my house " + verb_1 + " TV and playing on my" + noun_1 + ".")
print("I was very " + adj_2 + " for Christmas. I have gotten two awesome gifts: A " + noun_2 + " and a " + noun_3 + ".")
print("The entire time of my break, I would always go outside to " + verb_2 + " on my " + noun_4 + ".")
print("For new years, I had a big " + noun_5 + ", and I overall had a very " + adj_2 + " time!")